# Generated by Django 4.2.3 on 2023-07-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_for_delivery',
            field=models.DateField(),
        ),
    ]
