# Generated by Django 4.2.3 on 2023-07-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('year', models.IntegerField()),
                ('author', models.CharField(max_length=55)),
                ('in_stock', models.BooleanField(default=True)),
                ('time_added', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='img/%Y/%m/%d/%h/')),
                ('shelf', models.IntegerField()),
                ('slug', models.SlugField(max_length=455, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Future',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
