# Generated by Django 4.2.3 on 2023-07-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=155)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=555)),
                ('time_joining', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
